"""employee mangament

Revision ID: 280f46578180
Revises: 
Create Date: 2025-02-14 12:12:31.236288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '280f46578180'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('gender', sa.Enum('Male', 'Female', name='genderenum'), nullable=False),
    sa.Column('number', sa.String(length=10), nullable=False),
    sa.Column('phone_number', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('contract_type', sa.Enum('CDD', 'CDI', 'SIVP', name='contracttypeenum'), nullable=True),
    sa.Column('status_account', sa.Enum('Active', 'Suspended', 'Closed', name='statusaccountenum'), nullable=False),
    sa.Column('cnss_number', sa.String(length=11), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.CheckConstraint("(contract_type IN ('CDI', 'CDD') AND cnss_number ~ '^[0-9]{8}-[0-9]{2}$') OR (contract_type NOT IN ('CDI', 'CDD'))", name='cnss_required_for_cdi_cdd'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('number'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index(op.f('ix_employee_id'), 'employee', ['id'], unique=False)
    op.create_table('Acount_Activation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Employee_id', sa.Integer(), nullable=False),
    sa.Column('Email', sa.String(length=100), nullable=False),
    sa.Column('token', sa.String(length=100), nullable=True),
    sa.Column('expired_date', sa.Date(), nullable=True),
    sa.Column('token_status_id', sa.Enum('Valid', 'Expired', name='tokenstatusenum'), nullable=False),
    sa.ForeignKeyConstraint(['Employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Acount_Activation_id'), 'Acount_Activation', ['id'], unique=False)
    op.create_table('Change_Pasword',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Employee_id', sa.Integer(), nullable=False),
    sa.Column('expired_date', sa.Date(), nullable=True),
    sa.Column('token_status_id', sa.Enum('Valid', 'Expired', name='tokenstatusenum'), nullable=False),
    sa.ForeignKeyConstraint(['Employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Change_Pasword_id'), 'Change_Pasword', ['id'], unique=False)
    op.create_table('employee_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Employee_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'Inventory_Manager', 'Vendor', 'Superuser', name='roleenum'), nullable=False),
    sa.ForeignKeyConstraint(['Employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_role_id'), 'employee_role', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_role_id'), table_name='employee_role')
    op.drop_table('employee_role')
    op.drop_index(op.f('ix_Change_Pasword_id'), table_name='Change_Pasword')
    op.drop_table('Change_Pasword')
    op.drop_index(op.f('ix_Acount_Activation_id'), table_name='Acount_Activation')
    op.drop_table('Acount_Activation')
    op.drop_index(op.f('ix_employee_id'), table_name='employee')
    op.drop_table('employee')
    # ### end Alembic commands ###
