"""initial migration

Revision ID: 3b187f67fafc
Revises: 
Create Date: 2025-05-14 13:40:05.717237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b187f67fafc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('gender', sa.Enum('Male', 'Female', name='genderenum'), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('number', sa.String(length=11), nullable=False),
    sa.Column('phone_number', sa.String(length=11), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('contract_type', sa.Enum('CDD', 'CDI', 'SIVP', 'APPRNTI', name='contracttypeenum'), nullable=True),
    sa.Column('status_account', sa.Enum('Active', 'Inactive', name='statusaccountenum'), nullable=False),
    sa.Column('cnss_number', sa.String(length=11), nullable=True),
    sa.Column('created_at', sa.Date(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("((contract_type::text IN ('CDI', 'CDD') AND cnss_number IS NOT NULL AND cnss_number ~ '^[0-9]{8}-[0-9]{2}$') OR (contract_type::text IN ('SIVP', 'APPRENTI') AND cnss_number IS NULL))", name='cnss_required_for_cdi_cdd'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnss_number'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('number'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index(op.f('ix_employee_id'), 'employee', ['id'], unique=False)
    op.create_table('error',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.Date(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_error_id'), 'error', ['id'], unique=False)
    op.create_table('acount_activation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Employee_id', sa.Integer(), nullable=False),
    sa.Column('Email', sa.String(length=100), nullable=False),
    sa.Column('token', sa.String(length=100), nullable=False),
    sa.Column('created_on', sa.Date(), nullable=False),
    sa.Column('token_status_id', sa.Enum('Valid', 'Expired', name='tokenstatusenum'), nullable=False),
    sa.ForeignKeyConstraint(['Employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acount_activation_id'), 'acount_activation', ['id'], unique=False)
    op.create_table('change_password',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Employee_id', sa.Integer(), nullable=False),
    sa.Column('expired_date', sa.Date(), nullable=True),
    sa.Column('token', sa.String(length=100), nullable=False),
    sa.Column('token_status_id', sa.Enum('Valid', 'Expired', name='tokenstatusenum'), nullable=False),
    sa.ForeignKeyConstraint(['Employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_password_id'), 'change_password', ['id'], unique=False)
    op.create_table('employee_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Employee_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'Inventory_Manager', 'Vendor', 'Superuser', name='roleenum'), nullable=False),
    sa.ForeignKeyConstraint(['Employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_role_id'), 'employee_role', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_role_id'), table_name='employee_role')
    op.drop_table('employee_role')
    op.drop_index(op.f('ix_change_password_id'), table_name='change_password')
    op.drop_table('change_password')
    op.drop_index(op.f('ix_acount_activation_id'), table_name='acount_activation')
    op.drop_table('acount_activation')
    op.drop_index(op.f('ix_error_id'), table_name='error')
    op.drop_table('error')
    op.drop_index(op.f('ix_employee_id'), table_name='employee')
    op.drop_table('employee')
    # ### end Alembic commands ###
