"""add email change token 

Revision ID: 66c12809ffae
Revises: 3eddfc367b06
Create Date: 2025-06-15 14:23:59.304016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66c12809ffae'
down_revision: Union[str, None] = '3eddfc367b06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_change_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Employee_id', sa.Integer(), nullable=False),
    sa.Column('new_email', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['Employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_email_change_tokens_id'), 'email_change_tokens', ['id'], unique=False)
    op.alter_column('employee', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=15),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee', 'phone_number',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_index(op.f('ix_email_change_tokens_id'), table_name='email_change_tokens')
    op.drop_table('email_change_tokens')
    # ### end Alembic commands ###
